SCript SQL creacion de datos

TABLE:TAGS_TAB
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('1', '@pantalla')
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('2', '@habilidades')
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('3', '@BugClaro')
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('4', '@GrupoDeTrabajo')
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('5', '@BuscarGrupoTrabajo')
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('6', '@DeshabilitarGrupo')
INSERT INTO "WILDFLY"."TAGS_TAB" (TAG_ID, NAME) VALUES ('77', '@GrupoTrabajo')


TABLE:ESTATISTICA_REPORT_TAB
INSERT INTO "WILDFLY"."ESTATISTICA_REPORT_TAB" (ESTADISTICA_REPORT_ID, CONTADOR_FEATURE, CONTADOR_FLUJO, CONTADOR_PANTALLA) VALUES ('1', '100', '50', '50')
